-- 1. List all available products in stock
CALL ListAvailableProducts();

-- 2. Retrieve purchase history of a specific customer (example: customer ID = 5)
CALL GetCustomerPurchaseHistory(5);

-- 3. Find the most purchased product
CALL GetMostPurchasedProduct();

-- 5. Delete customer records (example: delete customer with ID = 34)
-- Make sure to delete dependent orders first or have ON DELETE CASCADE set
CALL DeleteCustomer(34);

-- 6. Generate a sales report
CALL GenerateSalesReport();

-- 7. Retrieve customers who placed orders in the last 3 months
CALL GetRecentCustomers();

-- 8. Find the total revenue generated by each category
CALL GetTotalRevenueByCategory();

-- 9. Retrieve the top 5 customers with the highest total purchase value
CALL GetTop5Customers();

-- 10. List products that are out of stock
CALL GetOutOfStockProducts();

-- 11. Find the most frequently bought product category
CALL GetMostFrequentCategory();

-- 12. Retrieve orders placed during a specific month 
CALL GetOrdersByMonth(2025, 3);

-- 13. Find the average order value per customer
CALL GetAverageOrderValue();

-- 14. Retrieve all orders with more than 5 items
CALL GetLargeOrders();

-- 15. Find customers who have never placed an order
CALL GetCustomersWithoutOrders();

-- 16. Retrieve orders sorted by highest total value
CALL GetOrdersByTotalValue();
